// Mocks generated by Mockito 5.4.4 from annotations
// in nexuspoint_pos/test/unit/auth_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nexuspoint_pos/core/api/api_service.dart' as _i3;
import 'package:nexuspoint_pos/core/models/api_models.dart' as _i2;
import 'package:nexuspoint_pos/core/models/branch_dto.dart' as _i5;
import 'package:nexuspoint_pos/core/models/table_dto.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResponse_0 extends _i1.SmartFake implements _i2.AuthResponse {
  _FakeAuthResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrderResponse_1 extends _i1.SmartFake implements _i2.OrderResponse {
  _FakeOrderResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrganization_2 extends _i1.SmartFake implements _i2.Organization {
  _FakeOrganization_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMenuWithModifiersDto_3 extends _i1.SmartFake
    implements _i2.MenuWithModifiersDto {
  _FakeMenuWithModifiersDto_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PosApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPosApiService extends _i1.Mock implements _i3.PosApiService {
  MockPosApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> requestOtp(String? email) => (super.noSuchMethod(
        Invocation.method(
          #requestOtp,
          [email],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.AuthResponse> verifyOtp(
    String? email,
    String? otp,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOtp,
          [
            email,
            otp,
          ],
        ),
        returnValue: _i4.Future<_i2.AuthResponse>.value(_FakeAuthResponse_0(
          this,
          Invocation.method(
            #verifyOtp,
            [
              email,
              otp,
            ],
          ),
        )),
      ) as _i4.Future<_i2.AuthResponse>);

  @override
  _i4.Future<_i2.OrderResponse> createOrder(_i2.OrderRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrder,
          [request],
        ),
        returnValue: _i4.Future<_i2.OrderResponse>.value(_FakeOrderResponse_1(
          this,
          Invocation.method(
            #createOrder,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.OrderResponse>);

  @override
  _i4.Future<void> updateOrderStatus({
    required String? orderId,
    required String? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrderStatus,
          [],
          {
            #orderId: orderId,
            #status: status,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> voidItem({
    required String? orderId,
    required String? orderItemId,
    required String? requesterId,
    String? approverId,
    String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #voidItem,
          [],
          {
            #orderId: orderId,
            #orderItemId: orderItemId,
            #requesterId: requesterId,
            #approverId: approverId,
            #reason: reason,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> voidOrder({
    required String? orderId,
    required String? requesterId,
    String? approverId,
    String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #voidOrder,
          [],
          {
            #orderId: orderId,
            #requesterId: requesterId,
            #approverId: approverId,
            #reason: reason,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.OrderResponse>> getOrders({
    required String? tenantId,
    required String? branchId,
    String? fromDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrders,
          [],
          {
            #tenantId: tenantId,
            #branchId: branchId,
            #fromDate: fromDate,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.OrderResponse>>.value(<_i2.OrderResponse>[]),
      ) as _i4.Future<List<_i2.OrderResponse>>);

  @override
  _i4.Future<Map<String, dynamic>> getSession() => (super.noSuchMethod(
        Invocation.method(
          #getSession,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<_i2.Organization>> getUserOrganizations() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserOrganizations,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.Organization>>.value(<_i2.Organization>[]),
      ) as _i4.Future<List<_i2.Organization>>);

  @override
  _i4.Future<void> setActiveOrganization(String? organizationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #setActiveOrganization,
          [organizationId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.Organization> createOrganization({
    required String? name,
    required String? slug,
    String? description,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrganization,
          [],
          {
            #name: name,
            #slug: slug,
            #description: description,
          },
        ),
        returnValue: _i4.Future<_i2.Organization>.value(_FakeOrganization_2(
          this,
          Invocation.method(
            #createOrganization,
            [],
            {
              #name: name,
              #slug: slug,
              #description: description,
            },
          ),
        )),
      ) as _i4.Future<_i2.Organization>);

  @override
  _i4.Future<List<_i2.MenuItemDto>> getMenuItems(String? tenantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMenuItems,
          [tenantId],
        ),
        returnValue:
            _i4.Future<List<_i2.MenuItemDto>>.value(<_i2.MenuItemDto>[]),
      ) as _i4.Future<List<_i2.MenuItemDto>>);

  @override
  _i4.Future<_i2.MenuWithModifiersDto> getMenuItemsWithModifiers() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMenuItemsWithModifiers,
          [],
        ),
        returnValue: _i4.Future<_i2.MenuWithModifiersDto>.value(
            _FakeMenuWithModifiersDto_3(
          this,
          Invocation.method(
            #getMenuItemsWithModifiers,
            [],
          ),
        )),
      ) as _i4.Future<_i2.MenuWithModifiersDto>);

  @override
  _i4.Future<void> updateMenuItem(
    String? id,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMenuItem,
          [
            id,
            updates,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.BranchDto>> getBranches() => (super.noSuchMethod(
        Invocation.method(
          #getBranches,
          [],
        ),
        returnValue: _i4.Future<List<_i5.BranchDto>>.value(<_i5.BranchDto>[]),
      ) as _i4.Future<List<_i5.BranchDto>>);

  @override
  _i4.Future<List<_i6.TableDto>> getFloorPlanTables(
    String? orgId,
    String? branchId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFloorPlanTables,
          [
            orgId,
            branchId,
          ],
        ),
        returnValue: _i4.Future<List<_i6.TableDto>>.value(<_i6.TableDto>[]),
      ) as _i4.Future<List<_i6.TableDto>>);

  @override
  _i4.Future<List<_i6.TableStatusDto>> getTableStatuses(
    String? orgId,
    String? branchId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTableStatuses,
          [
            orgId,
            branchId,
          ],
        ),
        returnValue:
            _i4.Future<List<_i6.TableStatusDto>>.value(<_i6.TableStatusDto>[]),
      ) as _i4.Future<List<_i6.TableStatusDto>>);
}
