// Mocks generated by Mockito 5.4.4 from annotations
// in nexuspoint_pos/test/unit/auth_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:nexuspoint_pos/core/api/api_service.dart' as _i3;
import 'package:nexuspoint_pos/core/models/api_models.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResponse_0 extends _i1.SmartFake implements _i2.AuthResponse {
  _FakeAuthResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrderResponse_1 extends _i1.SmartFake implements _i2.OrderResponse {
  _FakeOrderResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PosApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPosApiService extends _i1.Mock implements _i3.PosApiService {
  MockPosApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  _i5.Future<_i2.AuthResponse> login(_i2.LoginRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [request],
        ),
        returnValue: _i5.Future<_i2.AuthResponse>.value(_FakeAuthResponse_0(
          this,
          Invocation.method(
            #login,
            [request],
          ),
        )),
      ) as _i5.Future<_i2.AuthResponse>);

  @override
  _i5.Future<_i2.OrderResponse> createOrder(_i2.OrderRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrder,
          [request],
        ),
        returnValue: _i5.Future<_i2.OrderResponse>.value(_FakeOrderResponse_1(
          this,
          Invocation.method(
            #createOrder,
            [request],
          ),
        )),
      ) as _i5.Future<_i2.OrderResponse>);

  @override
  _i5.Future<List<_i2.OrderResponse>> getOrders({
    required String? tenantId,
    required String? branchId,
    String? fromDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrders,
          [],
          {
            #tenantId: tenantId,
            #branchId: branchId,
            #fromDate: fromDate,
          },
        ),
        returnValue:
            _i5.Future<List<_i2.OrderResponse>>.value(<_i2.OrderResponse>[]),
      ) as _i5.Future<List<_i2.OrderResponse>>);

  @override
  _i5.Future<List<_i2.MenuItemDto>> getMenuItems(String? tenantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMenuItems,
          [tenantId],
        ),
        returnValue:
            _i5.Future<List<_i2.MenuItemDto>>.value(<_i2.MenuItemDto>[]),
      ) as _i5.Future<List<_i2.MenuItemDto>>);

  @override
  _i5.Future<void> updateMenuItem(
    String? id,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMenuItem,
          [
            id,
            updates,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
